apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: http-server01
  name: http-server01
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: http-server01
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: http-server01
    spec:
      containers:
        - image: yusufselimgol/http-server:v2
          name: http-server01
          ports:
            - containerPort: 8000
              protocol: TCP
      hostname: http-server01
      restartPolicy: Always
