apiVersion: v1
data:
  nginx.conf: |+
    user nginx;

    events
    {
    	worker_connections 1000;
    }

    http
    {

    	upstream backendsrv
    	{
    		server 127.0.0.1:8000;
    	}
    	server
    	{
    		listen 8000;

    		location /
    		{
    			proxy_pass http://backendsrv;
    			proxy_set_header Host $host;
    			proxy_set_header X-Real-IP $remote_addr;
    			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    			proxy_set_header X-Forwarded-Proto $scheme;
    		}
    	}
    }

kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: nginx
  name: nginx-cm0
