version: 'v1'
services:
  http-server01:
    image: http-server:v2
    hostname: http-server01
    expose:
      - "8000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - http-server01
    ports:
      - "8000-8002:8000"
    deploy:
      replicas: 3

networks:
  default:
    driver: bridge
    name: http-server01
